<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Mono.Cecil">
      <HintPath>..\spacechase_mods\shared\SpaceShared.Mods.Harmony\Mono.Cecil.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
